# -*- coding: utf-8 -*-
"""Max Total Sales by Shipping Mode

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9t0fvnW0gjjOrTu6YhUneyB0MSASs9e
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import requests

shipping_df = pd.read_csv("SHIPPINGDATACSV.csv")
shipping_df

df_2015 = shipping_df[shipping_df['Year'] == 2015]


max_sales_info = df_2015.groupby('Shipping_Mode').apply(lambda x: x.loc[x['Total_Sales'].idxmax()])

# Plotting
fig, ax = plt.subplots(figsize=(10, 6))
bars = ax.bar(max_sales_info['Shipping_Mode'], max_sales_info['Total_Sales'], color='skyblue')

ax.set_xlabel('Shipping Mode')
ax.set_ylabel('Max Total Sales')
ax.set_title('Max Total Sales by Shipping Mode in 2015')

# Adding values and month annotations on top of bars
for bar, month in zip(bars, max_sales_info['Month']):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width() / 2, height, f'{height:.2f}', ha='center', va='bottom', color='black')
    ax.text(bar.get_x() + bar.get_width() / 2, height * 0.9, f'Month: {int(month)}', ha='center', va='top', color='black')

plt.xticks(rotation=0)  # Rotate x-axis labels for better readability
plt.tight_layout()
plt.show()

df_2016 = shipping_df[shipping_df['Year'] == 2016]

max_sales_info = df_2016.groupby('Shipping_Mode').apply(lambda x: x.loc[x['Total_Sales'].idxmax()])

# Plotting
fig, ax = plt.subplots(figsize=(10, 6))
bars = ax.bar(max_sales_info['Shipping_Mode'], max_sales_info['Total_Sales'], color='skyblue')

ax.set_xlabel('Shipping Mode')
ax.set_ylabel('Max Total Sales')
ax.set_title('Max Total Sales by Shipping Mode in 2016')

# Adding values and month annotations on top of bars
for bar, month in zip(bars, max_sales_info['Month']):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width() / 2, height, f'{height:.2f}', ha='center', va='bottom', color='black')
    ax.text(bar.get_x() + bar.get_width() / 2, height * 0.9, f'Month: {int(month)}', ha='center', va='top', color='black')

plt.xticks(rotation=0)  # Rotate x-axis labels for better readability
plt.tight_layout()
plt.show()

df_2017 = shipping_df[shipping_df['Year'] == 2017]
max_sales_info = df_2017.groupby('Shipping_Mode').apply(lambda x: x.loc[x['Total_Sales'].idxmax()])

# Plotting
fig, ax = plt.subplots(figsize=(10, 6))
bars = ax.bar(max_sales_info['Shipping_Mode'], max_sales_info['Total_Sales'], color='skyblue')

ax.set_xlabel('Shipping Mode')
ax.set_ylabel('Max Total Sales')
ax.set_title('Max Total Sales by Shipping Mode in 2017')

# Adding values and month annotations on top of bars
for bar, month in zip(bars, max_sales_info['Month']):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width() / 2, height, f'{height:.2f}', ha='center', va='bottom', color='black')
    ax.text(bar.get_x() + bar.get_width() / 2, height * 0.9, f'Month: {int(month)}', ha='center', va='top', color='black')

plt.xticks(rotation=0)  # Rotate x-axis labels for better readability
plt.tight_layout()
plt.show()

df_2018 = shipping_df[shipping_df['Year'] == 2018]

max_sales_info = df_2018.groupby('Shipping_Mode').apply(lambda x: x.loc[x['Total_Sales'].idxmax()])

# Plotting
fig, ax = plt.subplots(figsize=(10, 6))
bars = ax.bar(max_sales_info['Shipping_Mode'], max_sales_info['Total_Sales'], color='skyblue')

ax.set_xlabel('Shipping Mode')
ax.set_ylabel('Max Total Sales')
ax.set_title('Max Total Sales by Shipping Mode in 2018')

# Adding values and month annotations on top of bars
for bar, month in zip(bars, max_sales_info['Month']):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width() / 2, height, f'{height:.2f}', ha='center', va='bottom', color='black')
    ax.text(bar.get_x() + bar.get_width() / 2, height * 0.9, f'Month: {int(month)}', ha='center', va='top', color='black')

plt.xticks(rotation=0)  # Rotate x-axis labels for better readability
plt.tight_layout()
plt.show()

